language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t vinu3838/react-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true vinu3838/react-docker npm run test

